package roman.bannikov.aston_rick_and_morty.utils

class Const {
    companion object {

        const val BASE_URL = "https://rickandmortyapi.com/api/"
        const val DATABASE_NAME = "AppDB.bd"

        //NAVIGATION AND BACKSTACK

        //character
        const val TAG_CHARACTER_LIST_FRAGMENT = "TAG_CHARACTER_LIST_FRAGMENT"
        const val NAME_CHARACTER_LIST_FRAGMENT = "NAME_CHARACTER_LIST_FRAGMENT"
        const val TAG_CHARACTER_FILTER_FRAGMENT = "TAG_CHARACTER_FILTER_FRAGMENT"
        const val TAG_CHARACTER_DETAILS_FRAGMENT = "CHARACTER_DETAILS_FRAGMENT"
        const val NAME_CHARACTER_DETAILS_FRAGMENT = "NAME_CHARACTER_DETAILS_FRAGMENT"
        const val TAG_FILTERED_CHARACTER_LIST = "TAG_FILTERED_CHARACTER_LIST"
        const val NAME_FILTERED_CHARACTER_LIST = "NAME_FILTERED_CHARACTER_LIST"

        //episode
        const val TAG_EPISODE_LIST_FRAGMENT = "TAG_EPISODE_LIST_FRAGMENT"
        const val NAME_EPISODE_LIST_FRAGMENT = "NAME_EPISODE_LIST_FRAGMENT"
        const val TAG_EPISODE_FILTER_FRAGMENT = "TAG_EPISODE_FILTER_FRAGMENT"
        const val TAG_EPISODE_DETAILS_FRAGMENT = "TAG_EPISODE_DETAILS_FRAGMENT"
        const val NAME_EPISODE_DETAILS_FRAGMENT = "NAME_EPISODE_DETAILS_FRAGMENT"
        const val TAG_FILTERED_EPISODE_LIST = "TAG_FILTERED_EPISODE_LIST"
        const val NAME_FILTERED_EPISODE_LIST = "NAME_FILTERED_EPISODE_LIST"

        //location
        const val TAG_LOCATION_LIST_FRAGMENT = "TAG_LOCATION_LIST_FRAGMENT"
        const val NAME_LOCATION_LIST_FRAGMENT = "NAME_LOCATION_LIST_FRAGMENT"
        const val TAG_LOCATION_FILTER_FRAGMENT = "TAG_LOCATION_FILTER_FRAGMENT"
        const val TAG_LOCATION_DETAILS_FRAGMENT = "TAG_LOCATION_DETAILS_FRAGMENT"
        const val NAME_LOCATION_DETAILS_FRAGMENT = "NAME_LOCATION_DETAILS_FRAGMENT"
        const val TAG_FILTERED_LOCATION_LIST = "TAG_FILTERED_LOCATION_LIST"
        const val NAME_FILTERED_LOCATION_LIST = "NAME_FILTERED_LOCATION_LIST"
    }
}